Hash trie; for creating finite maps from sequences
cuplv/pmfp-collections.rust pull request #19
Opened 2017-08-07 13:10 UTC by matthewhammer

r @kyleheadley 
(following the Rust github conventions for requesting a review from @kyleheadley)

modules `trie1` and `trie2` are two variants of hash tries, for representing finite maps computed from sequences.  The second variant is similar, with comparable performance to the first.  In a later PR, I'll probably remove the first one and rename.

Performance
---------------

The image below shows that at 100k random `usize`s, constructing a Rust hashmap requires ~400ms to build (on my mac book air).  Meanwhile, it only takes 10ms to change propagate the trie construction algorithm after we edit the initial sequence.

![image](https://user-images.githubusercontent.com/1183963/29027545-5b708dcc-7b3e-11e7-8ef8-4e97cba94433.png)

To reproduce this, go into branch `dev-hammer`, under `eval` and do `cargo run --example unique_elms`.  I suspect that a more powerful computer may have similar, but slightly better results overall.

Commit history
------------------

I accidentally included a few commits (from `master`) of @kyleheadley below.  There's probably a way of correcting this, but it's easier just to recommit this time.  I know what I did, and how to avoid it next time (always do `git pull --rebase origin/master` before doing a PR, and don't pull without rebasing).

2017-08-07 13:16 UTC, matthewhammer commented on src/trie2.rs
> +//! Binary Hash Tries, for representing sets and finite maps.
r @kyleheadley 
This is the code that I really want reviewed.  The other `trie` variant (`trie.rs` and `trie1.rs`) above could probably be deleted.

2017-08-07 13:17 UTC, matthewhammer commented on src/trie2.rs
> +    fn join_rec (meta:TrieMeta, n:Option<Name>, lt: TrieRec<K,V>, rt: TrieRec<K,V>, bits:Bits) -> TrieRec<K,V> {
r @kyleheadley This is the core algorithm, which we've discussed in the past.

2017-08-07 18:20 UTC, kyleheadley requested changes
The requested change is to merge into dev instead of `master`. Any of our other new code would be there, and I think at lease quick hull was updated since.

The trie code (I only read trie2) looks well-polished, though lacking your usual extended commentary on technical detail. It's a shame you couldn't have used the existing level tree, but I can see that it doesn't match the code style here of directly working with the internal constructors.

I left some inline comments, but otherwise things look fine. I haven't looked any deeper at your algorithm, I assume the tests pass. I mostly looked for 'code quality' and anything that might interfere with my part of the codebase. Was there anything specific you wanted me to look at?

2017-08-07 18:20 UTC, kyleheadley commented on eval/Cargo.toml
> +#path = "/Users/hammer/repo/adapton.rust"
An oversight? There's an alternate solution [using .cargo/config](http://doc.crates.io/specifying-dependencies.html#overriding-with-local-dependencies), but I'm not sure if that's any easier to use.

2017-08-07 18:20 UTC, kyleheadley commented on eval/examples/unique_elms.rs
> +  // Warm up the Rust process in the OS:
You could also pull in the code that runs the tests multiple times and discards the first one. I changed quickhull to do that, but I don't see the changes above. Maybe they're in `dev` and haven't yet been pushed out to `master`.

2017-08-07 18:20 UTC, kyleheadley commented on src/trie2.rs
> +                    let mut vec = (*l.kvs).clone();
Optimization: make a `Vec::with_capacity()` and then `extend()` it with the left side before pushing the right. You'll avoid resizing on push.

2017-08-19 21:27 UTC, matthewhammer commented on eval/examples/unique_elms.rs
> +  // Warm up the Rust process in the OS:
Good idea!  I'd like to make that change, but maybe after this PR.

2017-08-19 21:29 UTC, matthewhammer commented
@kyleheadley I've "rebased" this PR, targeting `dev` (instead of `master`).

I've also added my latest _key value log_ module, `kvlog.rs`.

2017-08-21 19:11 UTC, kyleheadley approved these changes

2017-08-25 19:30 UTC, merged